In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))
print(a.shape)
print(a[0][2])
a[0,1]
print(a.size)
b=np.array([[[1,2,3],[3,4,5]],[[5,6,5],[7,8,9]],[[5,6,6],[7,8,9]]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
3
6
[[[1 2 3]
  [3 4 5]]

 [[5 6 5]
  [7 8 9]]

 [[5 6 6]
  [7 8 9]]]
3


In [2]:
a=np.zeros((3,3))
print(a)
c=np.ones((1,2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [3]:
d=np.full((2,3),5)
print(d)

[[5 5 5]
 [5 5 5]]


In [4]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
f=np.random.randint(1,6,(3,3))
print(f)

[[2 3 1]
 [2 3 3]
 [2 1 2]]


In [6]:
g=f[:,0]
print(g)

[2 2 2]


In [7]:
print(f[[0,1,2],[0,0,0]])

[2 2 2]


In [8]:
print(np.arange(4))

[0 1 2 3]


In [9]:
g= f[:,:]*2
print(g)

[[4 6 2]
 [4 6 6]
 [4 2 4]]


In [10]:
a1=f>2
print(a1)
print(f)
print(f[a1])

[[False  True False]
 [False  True  True]
 [False False False]]
[[2 3 1]
 [2 3 3]
 [2 1 2]]
[3 3 3]


In [11]:
a2=np.arange(4).reshape(2,1,2)
print(a2)

[[[0 1]]

 [[2 3]]]


In [12]:
a3=np.arange(3)
a4=np.full((1
        ,3),5)
print(a3)
print(a4)
np.dot(a4,a3)

[0 1 2]
[[5 5 5]]


array([15])

 x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [13]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [14]:
a=[1,7,3]
print(a.remove(0))


ValueError: list.remove(x): x not in list

In [ ]:
t=[True,1,2]
t.insert(2,5)
print(t)
print(sum(t))



In [ ]:
data = [2, 3, 9] 
temp =[[x for x in data if x>2] for x in range(3)] 
print (temp)

In [ ]:
L=[1,2,3,4]
print(L.remove(L[0]))
print(L)

In [ ]:
a=np.array([[1,2,3]])
print(a)
a.shape

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[4,5,6],[1,1,1]])
c=np.concatenate((a,b))
c

In [ ]:
np.vstack([a,b])

In [ ]:
myExample = {'someItem':2, 'otherItem':20}

In [ ]:
count=1
def a():
    global count
    for i in (1,2,3):
      count+=1
a()
print(count)

In [ ]:
a=[1,2,3,4]
b=[4,5,6,7]
a.extend(b)
a
import pandas as pd

In [ ]:
df = pd.DataFrame([['ff', 'gg', 'hh', 10],[24, 12,48, 30]],columns = ['Name', 'Age','x','y'] )
x=df.y.values
x=np.array([1 if y>10 else 0 for y in x])
x

In [ ]:
r = lambda q:q*2
a = lambda q:q*3
x=2
x=r(x)
x=a(x)
x=r(x)
print(x)

In [15]:
a=['ab','bc']
list(map(list,a))

[['a', 'b'], ['b', 'c']]

In [22]:
A=list(map(int,['1','2','3']))
A

[1, 2, 3]

In [96]:
a= np.array([1,2,3])
a.shape

(3,)

In [92]:
X = np.array([[1], [2], [3]])
y = np.array([[1], [2.5], [3.5]])

get_theta = lambda theta: np.array([[0, theta]])

thetas = list(map(get_theta, [0.5, 1.0, 1.5]))
X=np.hstack([np.ones([3,1]),X])


In [89]:
X

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [102]:
WE=np.arange(6)
WE=WE.reshape(6,1)
np.power(WE,2).sum()

55

In [1]:
import numpy as np

In [3]:
import pandas as pd
t = pd.read_csv("http://bit.ly/kaggletrain")
t.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [11]:
t.Sex.value_counts(dropna=False)
pd.get_dummies(t.Sex)

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [31]:
k=t[["Survived","Pclass"]].values

In [32]:
k=k[:-600,:]
k.shape
k

array([[0, 3],
       [1, 1],
       [1, 3],
       [1, 1],
       [0, 3],
       [0, 3],
       [0, 1],
       [0, 3],
       [1, 3],
       [1, 2],
       [1, 3],
       [1, 1],
       [0, 3],
       [0, 3],
       [0, 3],
       [1, 2],
       [0, 3],
       [1, 2],
       [0, 3],
       [1, 3],
       [0, 2],
       [1, 2],
       [1, 3],
       [1, 1],
       [0, 3],
       [1, 3],
       [0, 3],
       [0, 1],
       [1, 3],
       [0, 3],
       [0, 1],
       [1, 1],
       [1, 3],
       [0, 2],
       [0, 1],
       [0, 1],
       [1, 3],
       [0, 3],
       [0, 3],
       [1, 3],
       [0, 3],
       [0, 2],
       [0, 3],
       [1, 2],
       [1, 3],
       [0, 3],
       [0, 3],
       [1, 3],
       [0, 3],
       [0, 3],
       [0, 3],
       [0, 3],
       [1, 1],
       [1, 2],
       [0, 1],
       [1, 1],
       [1, 2],
       [0, 3],
       [1, 2],
       [0, 3],
       [0, 3],
       [1, 1],
       [0, 1],
       [0, 3],
       [0, 1],
       [1, 3],
       [1,

In [37]:
b=1
k.shape

(291, 2)

In [40]:
l=b+k

In [41]:
l[:3]

array([[1, 4],
       [2, 2],
       [2, 4]], dtype=int64)